#!/usr/bin/env python3


from lib import Rule


def main():
    try:
        print('Stupa main() called...')
        Rule.list_active()
    except Exception as e:
        print(e.args[0])


if __name__ == '__main__':
    main()
